# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Climate Compatible Growth Curation Guidelines
email: curation@climatecompatiblegrowth.com
description: >- # this means to ignore newlines until "baseurl:"
  Curation guidelines to support researchers, analysts, modellers and policy makers
  in the application of u4RIA and the Round Table Principles to energy planning
baseurl: "/guidelines/" # the subpath of your site, e.g. /blog
domain: climatecompatiblegrowth.github.io
url: "https://climatecompatiblegrowth.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ResearchCCG
github_username:  climatecompatiblegrowth

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: /:categories/:year/:month/:day/:title:output_ext
